= AsciidoctorJ Extensions for Firebird Documentation

image::https://github.com/mrotteveel/fb-asciidoctor-extensions/actions/workflows/run-tests.yml/badge.svg?branch=main[Build Status,link=https://github.com/mrotteveel/fb-asciidoctor-extensions/actions?query=branch%3Amain+workflow%3Arun-tests]

This is a collection of AsciidoctorJ extensions for use in https://github.com/FirebirdSQL/firebird-documentation[Firebird documentation], https://github.com/FirebirdSQL/jaybird[Jaybird release notes and FAQ] and the https://github.com/FirebirdSQL/jaybird-manual[Jaybird manual].

Code in this project is licensed under the https://www.firebirdsql.org/en/initial-developer-s-public-license-version-1-0/[Initial Developer's Public License Version 1.0] (IDPL), a derivative of the Mozilla Public License 1.1 (MPL-1.1).

SPDX-License-Identifier: LicenseRef-IDPL-1.0

== Available extensions

These extensions are registered automatically by AsciidoctorJ.

Current versions of the extensions work with AsciidoctorJ 3.0.x.

=== `canonical-link`

image::https://maven-badges.sml.io/sonatype-central/org.firebirdsql.asciidoctor/canonical-link/badge.svg?subject=canonical-link[canonical-link Maven info,link=https://maven-badges.sml.io/sonatype-central/org.firebirdsql.asciidoctor/canonical-link/]

Adds a canonical-link to HTML output, using the URL specified in document attribute `fb-canonical-html`.

For example, for a document with:

[source,asciidoc]
----
= Title
:fb-canonical-html: https://example.org/canonical.html

Body
----

This processor will add the following HTML fragment to the `<head>` element of the generated document:

[source,html]
----
<link rel="canonical" href="https://example.org/canonical.html"/>
----

.Maven coordinates
[source,xml]
----
<dependency>
  <groupId>org.firebirdsql.asciidoctor</groupId>
  <artifactId>canonical-link</artifactId>
  <version>1.1</version>
</dependency>
----

(Used in: https://github.com/FirebirdSQL/firebird-documentation[Firebird documentation], https://github.com/FirebirdSQL/jaybird[Jaybird release notes and FAQ], and the https://github.com/FirebirdSQL/jaybird-manual[Jaybird manual])

=== `since-until-macro`

image::https://maven-badges.sml.io/sonatype-central/org.firebirdsql.asciidoctor/since-until-macro/badge.svg?subject=since-until-macro[since-until-macro Maven info,link=https://maven-badges.sml.io/sonatype-central/org.firebirdsql.asciidoctor/since-until-macro/]

Provides two macros:

`++since:[<text>]++`::
`++since:[Jaybird 6]++` converts to `++[.since]_**Since:** Jaybird 6_++` (example rendering: [.since]_**Since:** Jaybird 6_)
`++until:[<text>]++`::
`++until:[Jaybird 6]++` converts to `++[.until]_**Removed in:** Jaybird 6_++` (example rendering: [.until]_**Removed in:** Jaybird 6_)

.Maven coordinates
[source,xml]
----
<dependency>
  <groupId>org.firebirdsql.asciidoctor</groupId>
  <artifactId>since-until-macro</artifactId>
  <version>1.1</version>
</dependency>
----

(Used in: the https://github.com/FirebirdSQL/jaybird-manual[Jaybird manual])

=== `issue-macro`

image::https://maven-badges.sml.io/sonatype-central/org.firebirdsql.asciidoctor/issue-macro/badge.svg?subject=issue-macro[issue-macro Maven info,link=https://maven-badges.sml.io/sonatype-central/org.firebirdsql.asciidoctor/issue-macro/]

Provides a simple macro to generate a GitHub Issues link, using the repository specified in the document attribute `fb-issue-repo`.

The macro is:

`++issue:[<issue-number>]++`

If _issue-number_ is not numeric, or `fb-issue-repo` has not been defined, the value is passed as-is.

For example, for a document with:

[source,asciidoc]
----
= title
:fb-issue-repo: FirebirdSQL/jaybird

See issue:[940].
----

It will generate the equivalent of:

[source,asciidoc]
----
= title
:fb-issue-repo: FirebirdSQL/jaybird

See https://github.com/FirebirdSQL/jaybird/issues/940[#940].
----

.Maven coordinates
[source,xml]
----
<dependency>
  <groupId>org.firebirdsql.asciidoctor</groupId>
  <artifactId>issue-macro</artifactId>
  <version>1.1</version>
</dependency>
----

(Used in: the https://github.com/FirebirdSQL/jaybird[Jaybird release notes])
